---
- name: Global GIT Config
  git_config:
    name: "{{ item.key }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - { key: user.name, value: "{{ user }}" }
    - { key: user.email, value: "{{ email }}" }
    - { key: commit.gpgsign, value: true }
    - { key: user.signingkey, value: "{{ email }}" }
