---
- name: Copy .gitconfig
  copy:
    src: files/.gitconfig
    dest: ~/.gitconfig
    mode: '0644'

- name: Copy git-personal.conf
  copy:
    src: files/git-personal.conf
    dest: ~/git-personal.conf
    mode: '0644'

- name: Copy git-infogrid.conf
  copy:
    src: files/git-infogrid.conf
    dest: ~/git-infogrid.conf
    mode: '0644'
