---
- name: Make SSH Directory
  file:
    path: ~/.ssh
    state: directory

- name: Generate an OpenSSH keypair
  become_user: "{{ name }}"
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_rsa
    comment: "{{ email }}"
