---
- name: Make SSH Directory
  file:
    path: ~/.ssh
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0700"
    state: directory

- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_rsa
    comment: "{{ email }}"
