---
- name: Add Signal Key
  become: yes
  apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    state: present

- name: Add Signal Repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    state: present

- name: Install Signal
  become: yes
  package:
    name:
      - signal-desktop
    state: present
