---
- name: Make Games Directory
  become: yes
  file:
    path: /home/games
    state: directory

- name: Mount Games Disk
  become: yes
  mount:
    path: /home/games
    src: LABEL=games
    fstype: ntfs
    state: present
