---
- name: Make Games Directory
  become: yes
  file:
    path: /home/games
    owner: root
    group: root
    mode: "0777"
    state: directory

- name: Mount Games Disk
  become: yes
  mount:
    path: /home/games
    src: LABEL=games-ssd
    fstype: ext4
    state: present
