---
- name: Install Drivers
  import_tasks: drivers.yml
  when: setup_drivers

- name: Setup Steam
  import_tasks: steam.yml

- name: Setup Lutris
  import_tasks: lutris.yml

- name: Setup Wine
  import_tasks: wine.yml

- name: Games Disk
  import_tasks: disk.yml
  when: setup_disk
