---
- name: Add Etcher Key
  become: yes
  apt_key:
    url: https://dl.cloudsmith.io/public/balena/etcher/gpg.70528471AFF9A051.key
    state: present

- name: Add Etcher Repository
  become: yes
  apt_repository:
    repo: deb https://dl.cloudsmith.io/public/balena/etcher/deb/ubuntu bionic main
    state: present

- name: Install Etcher
  become: yes
  package:
    name:
      - balena-etcher-electron
    state: present
