---
- name: Add Gcloud Key
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Gcloud Repository
  become: yes
  apt_repository:
    repo: deb https://packages.cloud.google.com/apt cloud-sdk main
    state: present

- name: Install Gcloud
  become: yes
  package:
    name:
      - google-cloud-sdk
    state: present
