---
- name: Download InfluxCLI
  unarchive:
    src: https://dl.influxdata.com/influxdb/releases/influxdb2_client_2.0.3_linux_amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install InfluxCLI
  become: yes
  copy:
    src: /tmp/influxdb2_client_2.0.3_linux_amd64/influx
    dest: /usr/local/bin/influx
    owner: root
    group: root
    mode: "0755"
