---
- name: Install Jenv Tools
  homebrew:
    name:
      - jenv
    state: present

- name: Make Jenv Directory
  file:
    path: ~/.jenv/versions
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: "0700"
    state: directory

- name: Download JDKs
  unarchive:
    src: "{{ item }}"
    dest: ~/.jenv/versions
    remote_src: yes
  loop:
    - https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u282-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u282b08.tar.gz
    - https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.10_9.tar.gz
