---
- name: Install kubectl
  homebrew:
    name:
      - kubectl
      - krew
    state: present

- name: Install FluxCD
  homebrew:
    name:
      - fluxcd/tap/flux
    state: present

- name: Install Kubeseal
  homebrew:
    name:
      - kubeseal
    state: present

- name: Install eksctl
  homebrew:
    name:
      - weaveworks/tap/eksctl
    state: present
