---
- name: Setup Utilities
  import_tasks: utilities.yml

- name: Setup Editors
  import_tasks: editors.yml

- name: Setup Docker
  import_tasks: docker.yml

- name: Setup Virtualbox
  import_tasks: virtualbox.yml

- name: Setup Python
  import_tasks: python.yml

- name: Setup Terraform
  import_tasks: terraform.yml
