---
- name: Install Utilities From Apt
  become: yes
  package:
    name:
      - git
      - make
      - hashdeep
      - shellcheck
      - vim
      - openvpn
    state: present

- name: Install Utilities From Deb
  become: yes
  apt:
    deb: "{{ item }}"
  loop:
    - https://prerelease.keybase.io/keybase_amd64.deb

- name: Install Utilities From Brew
  homebrew:
    name:
      - awscli
      - asdf
      - pre-commit
      - serverless
    state: present

- name: Install Utilities From Snap
  become: yes
  community.general.snap:
    name:
      - remmina
      - postman
