---
- name: Download installer
  get_url:
    url: https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb
    dest: /tmp/msfinstall
    mode: 0755

- name: Install Metasploit
  become: true
  command:
    cmd: /tmp/msfinstall
    creates: /opt/metasploit-framework/bin/msfconsole
