---
- name: Install Telegraf
  become: yes
  apt:
    deb: https://dl.influxdata.com/telegraf/releases/telegraf_1.17.0-1_amd64.deb

- name: Create telegraf.service.d directory
  become: yes
  file:
    path: /etc/systemd/system/telegraf.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Add override file
  become: yes
  copy:
    src: files/telegraf/override.conf
    dest: /etc/systemd/system/telegraf.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Telegraf

- name: Enable telegraf
  become: yes
  service:
    name: telegraf
    enabled: yes

- name: Add Telegraf User to Docker Group
  become: true
  user:
    name: telegraf
    groups: docker
    append: yes
